"""Todoga done qo'shish

Revision ID: 4aac71dd99e7
Revises: 
Create Date: 2025-01-17 15:31:05.835128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aac71dd99e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.add_column("todo", sa.Column("done", sa.Boolean(), default=False)) #Done degan ustun qo'shdim todo jadvaliga
    op.execute("UPDATE todo SET done = False WHERE done IS NULL")

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todo", "done") # todo jadvalidan done degan ustunni olib tashladim
    # ### end Alembic commands ###
